#!/usr/bin/env bash

# Wraps cli usage of google chrome on MacOS
# 
# Requirments: Google Chrome
#
# Run this script without arguments to trigger default state
#     Simple headless instance with remote debugging enabled
#     Debug address/port can be set using environment variables
#         Address: $CHROME_DEBUG_ADDRESS
#         Port:    $CHROME_DEBUG_PORT
#
# If this script is passed any arguments they will blindy be 
# passed to google chrome


if [[ ! -f "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" ]]; then
	echo "Google chrome not found"
	exit
fi

if [[ $# -eq 0 ]] ; then
	debugAddress=${CHROME_DEBUG_ADDRESS:-0.0.0.0}
	debugPort=${CHROME_DEBUG_PORT:-9222}

	echo "Running in default headless"
	echo "Debug Address: ${debugAddress}"
	echo "Debug Port: ${debugPort}"
	echo ""

	/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
else
	/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome $@
fi
